// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddScoreHandler(ReducerEventContext ctx, long amount);
        public event AddScoreHandler? OnAddScore;

        public void AddScore(long amount)
        {
            conn.InternalCallReducer(new Reducer.AddScore(amount));
        }

        public bool InvokeAddScore(ReducerEventContext ctx, Reducer.AddScore args)
        {
            if (OnAddScore == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddScore(
                ctx,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddScore : Reducer, IReducerArgs
        {
            [DataMember(Name = "amount")]
            public long Amount;

            public AddScore(long Amount)
            {
                this.Amount = Amount;
            }

            public AddScore()
            {
            }

            string IReducerArgs.ReducerName => "add_score";
        }
    }
}
