// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "score")]
        public long Score;
        [DataMember(Name = "online")]
        public bool Online;

        public Player(
            SpacetimeDB.Identity Identity,
            string Name,
            long Score,
            bool Online
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Score = Score;
            this.Online = Online;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
