// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
// 
// NOTE: Manually updated to match new server schema with anti-cheat fields.
// Re-run `spacetime generate` after deploying to get the canonical version.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "score")]
        public long Score;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "total_taps")]
        public long TotalTaps;
        [DataMember(Name = "last_action_timestamp_ms")]
        public long LastActionTimestampMs;
        [DataMember(Name = "actions_in_window")]
        public int ActionsInWindow;
        [DataMember(Name = "window_start_ms")]
        public long WindowStartMs;
        [DataMember(Name = "joined_at_ms")]
        public long JoinedAtMs;
        [DataMember(Name = "highest_score")]
        public long HighestScore;

        public Player(
            SpacetimeDB.Identity Identity,
            string Name,
            long Score,
            bool Online,
            long TotalTaps,
            long LastActionTimestampMs,
            int ActionsInWindow,
            long WindowStartMs,
            long JoinedAtMs,
            long HighestScore
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Score = Score;
            this.Online = Online;
            this.TotalTaps = TotalTaps;
            this.LastActionTimestampMs = LastActionTimestampMs;
            this.ActionsInWindow = ActionsInWindow;
            this.WindowStartMs = WindowStartMs;
            this.JoinedAtMs = JoinedAtMs;
            this.HighestScore = HighestScore;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
